# Generated by Django 3.2.16 on 2022-10-25 01:32

import django.utils.timezone
from django.db import migrations, models

import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatLightAssessment",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Canned Message", "Canned Message"),
                            ("LibraryH3lp Issue", "LibraryH3lp Issue"),
                            ("Library Website Issue", "Library Website Issue"),
                            ("Training", "Training"),
                            ("Unanswered", "Unanswered"),
                            ("Mentee", "Mentee"),
                            ("Ask Chat Policy", "Ask Chat Policy"),
                            ("Message to Operator", "Message to Operator"),
                            (
                                "Transcript Review Commitee",
                                "Transcript Review Commitee",
                            ),
                        ],
                        max_length=32,
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("lh3ChatID", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "categories",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "to_follow_up",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("operatorID", models.PositiveIntegerField(blank=True, null=True)),
                ("queueID", models.PositiveIntegerField(blank=True, null=True)),
                ("school", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "ordering": ("-lh3ChatID",),
            },
        ),
        migrations.CreateModel(
            name="chatReferenceQuestion",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("lh3ChatID", models.PositiveIntegerField(blank=True, null=True)),
                ("lh3guestID", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "ref_question_found",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "ref_question_position",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("operatorID", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "operator_username",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("queueID", models.PositiveIntegerField(blank=True, null=True)),
                ("queue_name", models.CharField(blank=True, max_length=50, null=True)),
                ("school", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "started_date",
                    models.DateTimeField(blank=True, default="", null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="flag",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("lh3ChatID", models.PositiveIntegerField(blank=True, null=True)),
                ("flag", models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                "ordering": ("-lh3ChatID",),
            },
        ),
        migrations.AddIndex(
            model_name="flag",
            index=models.Index(
                fields=["lh3ChatID"], name="dashboard_f_lh3Chat_365734_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatreferencequestion",
            index=models.Index(
                fields=["lh3ChatID", "queueID"], name="dashboard_c_lh3Chat_780c55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatlightassessment",
            index=models.Index(
                fields=["lh3ChatID", "queueID"], name="dashboard_c_lh3Chat_07252a_idx"
            ),
        ),
    ]
