# Generated by Django 3.2.21 on 2023-09-12 16:42

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatreferencequestion",
            name="lh3guestID",
        ),
        migrations.RemoveField(
            model_name="chatreferencequestion",
            name="operator_username",
        ),
        migrations.RemoveField(
            model_name="chatreferencequestion",
            name="school",
        ),
        migrations.RemoveField(
            model_name="chatreferencequestion",
            name="started_date",
        ),
    ]
