# Generated by Django 3.2.21 on 2023-09-19 14:36

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_auto_20230912_1242"),
    ]

    operations = [
        migrations.CreateModel(
            name="lh3DailyOffered",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username_id", models.CharField(blank=True, max_length=50, null=True)),
                ("hour", models.PositiveIntegerField(blank=True, null=True)),
                ("num_offered", models.PositiveIntegerField(blank=True, null=True)),
                ("num_answered", models.PositiveIntegerField(blank=True, null=True)),
                ("offered_date", models.DateField(blank=True, default="", null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name="lh3dailyoffered",
            index=models.Index(
                fields=["offered_date", "id"], name="dashboard_l_offered_eec4c5_idx"
            ),
        ),
    ]
